FROM alpine

# install curl and openssl
RUN apk --no-cache add curl openssl

# remove all trusted CAs
RUN rm /etc/ssl/cert.pem
RUN rm /etc/ssl/certs/*

# trust our self-signed cert
COPY server.crt /usr/local/share/ca-certificates/server.crt
RUN update-ca-certificates
